events {}

http {
    proxy_cache_path /var/cache/nginx
        keys_zone=demo_cache:10m
        inactive=60s
        max_size=100m;

    upstream app {
        server app:5000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://app;
        }

        location ~* \.(css|js|png|jpg|jpeg|gif)$ {
            proxy_pass http://app;

            proxy_cache demo_cache;

            proxy_cache_valid 200 60s;

            proxy_cache_key "$scheme$request_method$host$request_uri";

            add_header X-Cache-Status $upstream_cache_status;
        }
    }
}